name: Mobile analysis

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - GitHub Pages
    types:
      - completed
    branches:
      - main

jobs:
  analyze:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    uses: moritzbrantner/mobile-analysis/.github/workflows/analyze.yml@c80a2a8cf7d9611c34c047d0fc1555a0fbb6409a
    with:
      target_url: https://moritzbrantner.github.io/expo-template/
      config_path: mobile-analysis.config.json
      run_unlighthouse: true
